USE Employee
GO


IF OBJECT_ID('MAPEMPLOYEE','U') IS NULL
BEGIN
	CREATE TABLE MAPEMPLOYEE
	(
		ID INT PRIMARY KEY IDENTITY,		
		EMP_ID NVARCHAR(100) UNIQUE,
		First_Name NVARCHAR(100),
		Middle_Name NVARCHAR(100),
		Last_Name NVARCHAR(100),
		Extension_Name int FOREIGN KEY REFERENCES NAMINGEXTENSIONS(ID),
		Gender int FOREIGN KEY REFERENCES GENDERTABLE(ID),
		BirthDay date,
		Hired_At NVARCHAR(100),
		Resignes_At NVARCHAR(100),
	)
END
GO


--IF OBJECT_ID('MAPEMPLOYEE_DEPARTMENTS','U') IS NULL
--BEGIN
--	CREATE TABLE MAPEMPLOYEE_DEPARTMENTS
--	(
--		ID INT PRIMARY KEY IDENTITY,		
--		EMP_ID NVARCHAR(100) FOREIGN KEY REFERENCES MAPEMPLOYEE(EMP_ID),
--		Department_ID INT FOREIGN KEY REFERENCES DEPARMENTS(ID),
--		Resignes_At bit,
--	)
--END
--GO


IF OBJECT_ID('MAPEMPLOYEE_DEPENDENS','U') IS NULL
BEGIN
	CREATE TABLE MAPEMPLOYEE_DEPENDENS
	(
		ID INT PRIMARY KEY IDENTITY,		
		EMP_ID NVARCHAR(100) FOREIGN KEY REFERENCES MAPEMPLOYEE(EMP_ID),
		Name NVARCHAR(100),
		Gender int FOREIGN KEY REFERENCES GENDERTABLE(ID),
		BirthDay date,
		Relationship NVARCHAR(100),
	)
END
GO


--IF OBJECT_ID('MAPEMPLOYEE_POSITIONS','U') IS NULL
--BEGIN
--	CREATE TABLE MAPEMPLOYEE_POSITIONS
--	(
--		ID INT PRIMARY KEY IDENTITY,		
--		EMP_ID NVARCHAR(100) FOREIGN KEY REFERENCES MAPEMPLOYEE(EMP_ID),
--		Position_ID INT FOREIGN KEY REFERENCES POSITIONS(ID),
--		[Current] bit,
--	)
--END
--GO


IF OBJECT_ID('MAPEMPLOYEE_ADDRESS','U') IS NULL
BEGIN
	CREATE TABLE MAPEMPLOYEE_ADDRESS
	(
		ID INT PRIMARY KEY IDENTITY,		
		EMP_ID NVARCHAR(100) FOREIGN KEY REFERENCES MAPEMPLOYEE(EMP_ID),
		Province_ID int FOREIGN KEY REFERENCES PROVINCES(ID),
		Mulcipalty_ID int FOREIGN KEY REFERENCES MULCIPALTIES(ID),
		Barangay_ID int FOREIGN KEY REFERENCES BARANGAYS(ID),
		Street NVARCHAR(100),
		House_Number NVARCHAR(100),
		Permenant bit,
	)
END
GO


IF OBJECT_ID('BARANGAYS','U') IS NULL
BEGIN
	CREATE TABLE BARANGAYS
	(
		ID INT PRIMARY KEY IDENTITY,
		Mulcipalty_ID INT FOREIGN KEY REFERENCES MULCIPALTIES(ID),
		NAME NVARCHAR(100),
	)
END
GO


IF OBJECT_ID('MULCIPALTIES','U') IS NULL
BEGIN
	CREATE TABLE MULCIPALTIES
	(
		ID INT PRIMARY KEY IDENTITY,
		Province_ID INT FOREIGN KEY REFERENCES PROVINCES(Name),
		NAME NVARCHAR(100),
		Zip_Code NVARCHAR(100),
	)
END
GO


IF OBJECT_ID('PROVINCES','U') IS NULL
BEGIN
	CREATE TABLE PROVINCES
	(
		ID INT PRIMARY KEY IDENTITY,
		NAME NVARCHAR(100),
	)
END
GO


IF OBJECT_ID('DEPARMENTS','U') IS NULL
BEGIN
	CREATE TABLE DEPARMENTS
	(
		ID INT PRIMARY KEY IDENTITY,
		NAME NVARCHAR(100),
	)
END
GO


IF OBJECT_ID('POSITIONS','U') IS NULL
BEGIN
	CREATE TABLE POSITIONS
	(
		ID INT PRIMARY KEY IDENTITY,
		NAME NVARCHAR(100),
	)
END
GO


IF OBJECT_ID('NAMINGEXTENSIONS','U') IS NULL
BEGIN
	CREATE TABLE NAMINGEXTENSIONS
	(
		ID INT PRIMARY KEY IDENTITY,
		NAME NVARCHAR(100),
	)
END
GO


IF OBJECT_ID('GENDERTABLE','U') IS NULL
BEGIN
	CREATE TABLE GENDERTABLE
	(
		ID INT PRIMARY KEY IDENTITY,
		GENDER NVARCHAR(100),
	)
END
GO