USE [SUPPORT_DATA]
GO

/****** Object:  StoredProcedure [dbo].[UPDATE_SUPPORT]    Script Date: 18-11-2023 20:22:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[UPDATE_SUPPORT]
@SUPPORT_KEY NVARCHAR(100),
@SUPPORT_ALT_CODE NVARCHAR(100),
@SUPPORT_EXECUTION NVARCHAR(100),
@CLIENT_CATOGORY NVARCHAR(100),
@CLIENT_NAME NVARCHAR(100),
@PERSON_NAME NVARCHAR(100),
@PERSON_DEPARTMENT NVARCHAR(100),
@PHONE_NUMBER NVARCHAR(100),
@QUERY_TYPE NVARCHAR(100),
@QUERY_DESCRIPTION NVARCHAR(100),
@ANYDESK_NUMBER NVARCHAR(100),
@START_TIME NVARCHAR(100),
@END_TIME NVARCHAR(100),
@STATUS NVARCHAR(1),
@UPDATED_BY NVARCHAR(1),
@UPDATED_DATE NVARCHAR(100) = GETDATE
AS
BEGIN

UPDATE SUPPORT
SET
SUPPORT_ALT_CODE = @SUPPORT_ALT_CODE,
SUPPORT_EXECUTION = @SUPPORT_EXECUTION,
CLIENT_CATOGORY = @CLIENT_CATOGORY,
CLIENT_NAME = @CLIENT_NAME,
PERSON_NAME = @PERSON_NAME,
PERSON_DEPARTMENT = @PERSON_DEPARTMENT,
PHONE_NUMBER = @PHONE_NUMBER,
QUERY_TYPE = @QUERY_TYPE,
QUERY_DESCRIPTION = @QUERY_DESCRIPTION,
ANYDESK_NUMBER = @ANYDESK_NUMBER,
START_TIME = @START_TIME,
END_TIME = @END_TIME,
STATUS = @STATUS,
UPDATED_BY = @UPDATED_BY,
UPDATED_DATE = GETDATE()

WHERE SUPPORT_KEY = @SUPPORT_KEY
END
GO


