USE [SUPPORT_DATA]
GO

/****** Object:  StoredProcedure [dbo].[DELETE_SUPPORT]    Script Date: 18-11-2023 20:21:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DELETE_SUPPORT]
@SUPPORT_KEY NVARCHAR(100)
AS
BEGIN

DELETE SUPPORT WHERE SUPPORT_KEY = @SUPPORT_KEY

END
GO


