USE [SUPPORT_DATA]
GO

/****** Object:  Table [dbo].[SUPPORT]    Script Date: 18-11-2023 20:20:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SUPPORT](
	[SUPPORT_KEY] [nvarchar](100) NOT NULL,
	[SUPPORT_ALT_CODE] [nvarchar](100) NULL,
	[SUPPORT_EXECUTION] [nvarchar](100) NULL,
	[CLIENT_CATOGORY] [nvarchar](100) NULL,
	[CLIENT_NAME] [nvarchar](100) NULL,
	[PERSON_NAME] [nvarchar](100) NULL,
	[PERSON_DEPARTMENT] [nvarchar](100) NULL,
	[PHONE_NUMBER] [nvarchar](100) NULL,
	[QUERY_TYPE] [nvarchar](100) NULL,
	[QUERY_DESCRIPTION] [nvarchar](100) NULL,
	[ANYDESK_NUMBER] [nvarchar](100) NULL,
	[START_TIME] [nvarchar](100) NULL,
	[END_TIME] [nvarchar](100) NULL,
	[STATUS] [nvarchar](1) NULL,
	[CREATED_BY] [nvarchar](1) NULL,
	[CREATED_DATE] [date] NULL,
	[UPDATED_BY] [nvarchar](1) NULL,
	[UPDATED_DATE] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[SUPPORT_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


