USE Employee
GO

IF OBJECT_ID('SPINSERTINTO_TBLEMPLOYEE','P') IS NOT NULL
BEGIN
	DROP PROCEDURE SPINSERTINTO_TBLEMPLOYEE
END
GO
CREATE PROCEDURE SPINSERTINTO_TBLEMPLOYEE
(
	@NAME NVARCHAR(100),
	@EMP_ID NVARCHAR(100),
	@EMP_MANAGER NVARCHAR(100),
	@PHONE_NUMBER NVARCHAR(100),
	@EMP_JOINED_DATE DATE = GETDATE,
	@EMP_CONFIRM_DATE DATE = GETDATE
)
AS
BEGIN
	INSERT INTO TBLEMPLOYEE VALUES(@NAME,@EMP_ID,@EMP_MANAGER,@PHONE_NUMBER,@EMP_JOINED_DATE,@EMP_CONFIRM_DATE)
END
GO


IF OBJECT_ID('SPUPDATE_TBLEMPLOYEE','P') IS NOT NULL
BEGIN
	DROP PROCEDURE SPUPDATE_TBLEMPLOYEE
END
GO
CREATE PROCEDURE SPUPDATE_TBLEMPLOYEE
(
	@NAME NVARCHAR(100),
	@EMP_ID NVARCHAR(100),
	@EMP_MANAGER NVARCHAR(100),
	@PHONE_NUMBER NVARCHAR(100),
	@EMP_JOINED_DATE DATE = GETDATE,
	@EMP_CONFIRM_DATE DATE = GETDATE
)
AS
BEGIN
	UPDATE TBLEMPLOYEE SET NAME = @NAME ,EMP_MANAGER = @EMP_MANAGER,PHONE_NUMBER = @PHONE_NUMBER,
	EMP_JOINED_DATE = @EMP_JOINED_DATE,EMP_CONFIRM_DATE = @EMP_CONFIRM_DATE WHERE EMP_ID= @EMP_ID
END
GO


IF OBJECT_ID('SPDELETE_TBLEMPLOYEE','P') IS NOT NULL
BEGIN
	DROP PROCEDURE SPDELETE_TBLEMPLOYEE
END
GO
CREATE PROCEDURE SPDELETE_TBLEMPLOYEE
(
	@EMP_ID NVARCHAR(100)
)
AS
BEGIN
	DELETE TBLEMPLOYEE WHERE EMP_ID= @EMP_ID 
END
GO