USE Employee
GO


DECLARE @SQLCMD_INSERT NVARCHAR(MAX);
SET @SQLCMD_INSERT = N'IF OBJECT_ID(''SPINSERTINTO_TBLEMPLOYEE'',''P'') IS NOT NULL
BEGIN
	DROP PROCEDURE SPINSERTINTO_TBLEMPLOYEE
END
GO
CREATE PROCEDURE SPINSERTINTO_TBLEMPLOYEE
(
	@NAME NVARCHAR(100),
	@EMP_ID NVARCHAR(100),
	@EMP_MANAGER NVARCHAR(100),
	@PHONE_NUMBER NVARCHAR(100),
	@EMP_JOINED_DATE DATE,
	@EMP_CONFIRM_DATE DATE
)
AS
BEGIN
	INSERT INTO TBLEMPLOYEE VALUES(@NAME,@EMP_ID,@EMP_MANAGER,@PHONE_NUMBER,@EMP_JOINED_DATE,@EMP_CONFIRM_DATE)
END
GO'
EXEC SP_EXECUTESQL @SQLCMD_INSERT

DECLARE @SQLCMD_UPDATE NVARCHAR(MAX);
SET @SQLCMD_UPDATE = N'IF OBJECT_ID(''SPUPDATE_TBLEMPLOYEE'',''P'') IS NOT NULL
BEGIN
	DROP PROCEDURE SPUPDATE_TBLEMPLOYEE
END
GO
CREATE PROCEDURE SPUPDATE_TBLEMPLOYEE
(
	@NAME NVARCHAR(100),
	@EMP_ID NVARCHAR(100),
	@EMP_MANAGER NVARCHAR(100),
	@PHONE_NUMBER NVARCHAR(100),
	@EMP_JOINED_DATE DATE,
	@EMP_CONFIRM_DATE DATE
)
AS
BEGIN
	UPDATE TBLEMPLOYEE SET NAME = @NAME ,EMP_MANAGER = @EMP_MANAGER,PHONE_NUMBER = @PHONE_NUMBER,
	EMP_JOINED_DATE = @EMP_JOINED_DATE,EMP_CONFIRM_DATE = @EMP_CONFIRM_DATE WHERE EMP_ID= @EMP_ID
END
GO'
EXEC SP_EXECUTESQL @SQLCMD_UPDATE


DECLARE @SQLCMD_DELETE NVARCHAR(MAX);
SET @SQLCMD_DELETE = N'IF OBJECT_ID(''SPDELETE_TBLEMPLOYEE'',''P'') IS NOT NULL
BEGIN
	DROP PROCEDURE SPDELETE_TBLEMPLOYEE
END
GO
CREATE PROCEDURE SPDELETE_TBLEMPLOYEE
(
	@EMP_ID NVARCHAR(100)
)
AS
BEGIN
	DELETE TBLEMPLOYEE WHERE EMP_ID= @EMP_ID 
END
GO'
EXEC SP_EXECUTESQL @SQLCMD_DELETE