USE Employee
GO

IF OBJECT_ID('TBLEMPLOYEE','U') IS NULL
BEGIN
	CREATE TABLE TBLEMPLOYEE
	(
		ID INT PRIMARY KEY IDENTITY,
		NAME NVARCHAR(100),
		EMP_ID NVARCHAR(100) UNIQUE,
		EMP_MANAGER NVARCHAR(100),
		PHONE_NUMBER NVARCHAR(100),
		EMP_JOINED_DATE DATE,
		EMP_CONFIRM_DATE DATE
	)
END
GO

--IF OBJECT_ID('TBLEMPLOYEE','U') IS NULL
--BEGIN
--	DROP TABLE TBLEMPLOYEE
--END
--GO


--INSERT INTO TBLEMPLOYEE VALUES('RITIK','PCK01','RITIK','9967493553',GETDATE(),GETDATE())
--INSERT INTO TBLEMPLOYEE VALUES('ROSHAN','PCK02','RITIK','889554566',GETDATE(),GETDATE())
--INSERT INTO TBLEMPLOYEE VALUES('OMKAR','PCK03','RITIK','8875221333',GETDATE(),GETDATE())
--INSERT INTO TBLEMPLOYEE VALUES('KIRAN','PCK04','RITIK','45546623232',GETDATE(),GETDATE())
--INSERT INTO TBLEMPLOYEE VALUES('SRUSHTI','PCK05','RITIK','994555222',GETDATE(),GETDATE())
--INSERT INTO TBLEMPLOYEE VALUES('SWAPNALI','PCK06','RITIK','7542522162',GETDATE(),GETDATE())
--INSERT INTO TBLEMPLOYEE VALUES('VINIT','PCK07','RITIK','65556525233',GETDATE(),GETDATE())
--INSERT INTO TBLEMPLOYEE VALUES('KAJAL','PCK08','RITIK','55866555556',GETDATE(),GETDATE())